In [49]:
import pandas as pd

In [50]:
concordant = pd.read_csv("./Rules Clusters/ANSTAT_tous_non_concordants.csv")
clust = pd.read_csv("./assigned_clusters_manual_rules.csv")

In [51]:
concordant

,agro_zone,region_name,department,city,milieu_resid,hhweight,resid,sex,age_num,lien,...,bancarise,volhor_manquant,salaire_mois_manquant,Stg_formel,age_group,cluster_assigned,match_score,cluster_initial,cluster_predit,concordance
0,ABIDJAN,AUTONOME D'ABIDJAN,ABIDJAN,ABIDJAN,Urbain,1098.11720,Oui,Masculin,56,Chef de ménage,...,1,0,1,0,55-64,11,7,56,11,False
1,ABIDJAN,AUTONOME D'ABIDJAN,ABIDJAN,ABIDJAN,Urbain,1098.11720,Oui,Masculin,38,Chef de ménage,...,1,0,0,0,35-44,Aucun,0,94,Aucun,False
2,ABIDJAN,AUTONOME D'ABIDJAN,ABIDJAN,ABIDJAN,Urbain,1098.11720,Oui,Masculin,55,Chef de ménage,...,1,0,1,0,55-64,Aucun,0,56,Aucun,False
3,ABIDJAN,AUTONOME D'ABIDJAN,ABIDJAN,ABIDJAN,Urbain,962.40546,Oui,Masculin,42,Chef de ménage,...,1,0,1,0,35-44,Aucun,0,94,Aucun,False
4,ABIDJAN,AUTONOME D'ABIDJAN,ABIDJAN,ABIDJAN,Urbain,962.40546,Oui,Masculin,37,Chef de ménage,...,1,0,1,0,35-44,Aucun,0,94,Aucun,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24960,CENTRE,MORONOU,M'BATTO,TIEMELEKRO,Rural,242.77960,Oui,Masculin,55,Chef de ménage,...,1,0,1,0,55-64,13,7,52,13,False
24961,CENTRE,MORONOU,M'BATTO,TIEMELEKRO,Rural,242.77960,Oui,Masculin,36,Chef de ménage,...,1,0,1,0,35-44,52,7,85,52,False
24962,CENTRE,MORONOU,M'BATTO,TIEMELEKRO,Rural,242.77960,Oui,Féminin,33,Conjoint ( e ),...,0,0,1,0,25-34,Aucun,0,6,Aucun,False
24963,CENTRE,MORONOU,M'BATTO,TIEMELEKRO,Rural,242.77960,Oui,Féminin,37,Conjoint ( e ),...,0,1,1,0,35-44,Aucun,0,24,Aucun,False
24964,CENTRE,MORONOU,M'BATTO,TIEMELEKRO,Rural,242.77960,Oui,Masculin,36,Chef de ménage,...,1,0,1,0,35-44,52,7,85,52,False

In [52]:
concord = concordant[concordant["cluster_predit"]=="Aucun"]
concord

,agro_zone,region_name,department,city,milieu_resid,hhweight,resid,sex,age_num,lien,...,bancarise,volhor_manquant,salaire_mois_manquant,Stg_formel,age_group,cluster_assigned,match_score,cluster_initial,cluster_predit,concordance
1,ABIDJAN,AUTONOME D'ABIDJAN,ABIDJAN,ABIDJAN,Urbain,1098.11720,Oui,Masculin,38,Chef de ménage,...,1,0,0,0,35-44,Aucun,0,94,Aucun,False
2,ABIDJAN,AUTONOME D'ABIDJAN,ABIDJAN,ABIDJAN,Urbain,1098.11720,Oui,Masculin,55,Chef de ménage,...,1,0,1,0,55-64,Aucun,0,56,Aucun,False
3,ABIDJAN,AUTONOME D'ABIDJAN,ABIDJAN,ABIDJAN,Urbain,962.40546,Oui,Masculin,42,Chef de ménage,...,1,0,1,0,35-44,Aucun,0,94,Aucun,False
4,ABIDJAN,AUTONOME D'ABIDJAN,ABIDJAN,ABIDJAN,Urbain,962.40546,Oui,Masculin,37,Chef de ménage,...,1,0,1,0,35-44,Aucun,0,94,Aucun,False
6,ABIDJAN,AUTONOME D'ABIDJAN,ABIDJAN,ABIDJAN,Urbain,634.11560,Oui,Féminin,50,Conjoint ( e ),...,1,0,1,0,45-54,Aucun,0,22,Aucun,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24952,CENTRE,MORONOU,M'BATTO,TIEMELEKRO,Rural,242.77960,Oui,Masculin,0,"Fils, Fille",...,0,1,1,0,NaN,Aucun,0,89,Aucun,False
24954,CENTRE,MORONOU,M'BATTO,TIEMELEKRO,Rural,242.77960,Oui,Masculin,26,Neveu/Nièce,...,0,1,1,0,25-34,Aucun,0,89,Aucun,False
24959,CENTRE,MORONOU,M'BATTO,TIEMELEKRO,Rural,242.77960,Oui,Masculin,65,Chef de ménage,...,1,1,1,0,65-74,Aucun,0,13,Aucun,False
24962,CENTRE,MORONOU,M'BATTO,TIEMELEKRO,Rural,242.77960,Oui,Féminin,33,Conjoint ( e ),...,0,0,1,0,25-34,Aucun,0,6,Aucun,False
24963,CENTRE,MORONOU,M'BATTO,TIEMELEKRO,Rural,242.77960,Oui,Féminin,37,Conjoint ( e ),...,0,1,1,0,35-44,Aucun,0,24,Aucun,False

In [53]:
concord.columns

Index(['agro_zone', 'region_name', 'department', 'city', 'milieu_resid',
       'hhweight', 'resid', 'sex', 'age_num', 'lien', 'marital_status',
       'religion', 'ethnie', 'nation', 'agemar', 'mal30j', 'aff30j', 'arrmal',
       'durarr', 'con30j', 'hos12m', 'couvmal', 'handit', 'handig', 'alfa',
       'alfa2', 'scol', 'educ_scol', 'educ_hi', 'diplome', 'telpor',
       'internet', 'activ7j', 'activ12m', 'branch', 'sectins', 'csp', 'volhor',
       'salaire', 'emploi_sec', 'sectins_sec', 'csp_sec', 'volhor_sec',
       'salaire_sec', 'serviceconsult', 'persconsult', 'salaire_mois',
       'salaire_sec_mois', 'rev_total_mois', 'log_revenu', 'sans_revenu',
       'age_grp', 'a_assurance', 'alphabete', 'logem', 'elec_ac', 'elec_ur',
       'elec_ua', 'tv', 'fer', 'frigo', 'cuisin', 'ordin', 'decod', 'car',
       'superf', 'bancarise', 'volhor_manquant', 'salaire_mois_manquant',
       'Stg_formel', 'age_group', 'cluster_assigned', 'match_score',
       'cluster_initial', 'cluster_predit', 'concordance'],
      dtype='object')

In [54]:
concord = concord.drop(['agro_zone', 'department','hhweight', 'resid', 'lien',
       'religion', 'ethnie', 'nation', 'agemar', 'mal30j', 'aff30j', 'arrmal',
       'durarr', 'con30j', 'hos12m', 'couvmal', 'handit', 'handig', 'alfa',
       'alfa2', 'scol', 'educ_scol', 'educ_hi', 'diplome', 'telpor',
       'internet', 'activ7j', 'activ12m', 'branch', 'sectins', 'csp', 'volhor',
       'salaire', 'emploi_sec', 'sectins_sec', 'csp_sec', 'volhor_sec',
       'salaire_sec', 'serviceconsult', 'persconsult', 'salaire_mois',
       'salaire_sec_mois', 'rev_total_mois', 'log_revenu', 'sans_revenu',
       'age_grp', 'a_assurance', 'alphabete', 'logem', 'elec_ac', 'elec_ur',
       'elec_ua', 'tv', 'fer', 'frigo', 'cuisin', 'ordin', 'decod', 'car',
       'superf', 'volhor_manquant', 'salaire_mois_manquant',
       'Stg_formel', 'age_group', 'cluster_assigned', 'match_score',
       'cluster_initial', 'cluster_predit', 'concordance'], axis=1)
concord

,region_name,city,milieu_resid,sex,age_num,marital_status,bancarise
1,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,38,Célibataire,1
2,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,55,Célibataire,1
3,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,42,Célibataire,1
4,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,37,Célibataire,1
6,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Féminin,50,Union libre,1
...,...,...,...,...,...,...,...
24952,MORONOU,TIEMELEKRO,Rural,Masculin,0,Célibataire,0
24954,MORONOU,TIEMELEKRO,Rural,Masculin,26,Célibataire,0
24959,MORONOU,TIEMELEKRO,Rural,Masculin,65,Veuf(ve),1
24962,MORONOU,TIEMELEKRO,Rural,Féminin,33,Marié(e),0
24963,MORONOU,TIEMELEKRO,Rural,Féminin,37,Marié(e),0

In [55]:
clust

,cluster,age_num,sex,marital_status,city,milieu_resid,region_name,bancarise,age_group,predicted_cluster
0,17,29,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1,25-34,17
1,12,17,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,15-24,12
2,1,15,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,15-24,1
3,12,12,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,0-14,12
4,22,34,Féminin,Marié(e),ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,25-34,22
...,...,...,...,...,...,...,...,...,...,...
64469,89,11,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,0-14,89
64470,89,7,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,0-14,89
64471,89,10,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,0-14,89
64472,89,4,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,0-14,89
64473,85,36,Masculin,Marié(e),TIEMELEKRO,Rural,MORONOU,1,35-44,52

In [56]:
clust.columns

Index(['cluster', 'age_num', 'sex', 'marital_status', 'city', 'milieu_resid',
       'region_name', 'bancarise', 'age_group', 'predicted_cluster'],
      dtype='object')

In [57]:
clust = clust.drop(['predicted_cluster', 'age_group'], axis=1)
clust

,cluster,age_num,sex,marital_status,city,milieu_resid,region_name,bancarise
0,17,29,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1
1,12,17,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0
2,1,15,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0
3,12,12,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0
4,22,34,Féminin,Marié(e),ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0
...,...,...,...,...,...,...,...,...
64469,89,11,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0
64470,89,7,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0
64471,89,10,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0
64472,89,4,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0
64473,85,36,Masculin,Marié(e),TIEMELEKRO,Rural,MORONOU,1

In [58]:
inner_merged = pd.merge(clust, concord ,how="inner",on=["marital_status", "bancarise", "city", "milieu_resid", "age_num", "sex", "region_name"])
inner_merged

,cluster,age_num,sex,marital_status,city,milieu_resid,region_name,bancarise
0,94,38,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1
1,94,38,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1
2,94,38,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1
3,94,38,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1
4,94,38,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1
...,...,...,...,...,...,...,...,...
39329,89,0,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0
39330,89,26,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0
39331,13,65,Masculin,Veuf(ve),TIEMELEKRO,Rural,MORONOU,1
39332,6,33,Féminin,Marié(e),TIEMELEKRO,Rural,MORONOU,0
39333,24,37,Féminin,Marié(e),TIEMELEKRO,Rural,MORONOU,0

In [59]:
cles = ["marital_status", "bancarise", "city", "milieu_resid", "age_num", "sex", "region_name"]

# Construire une clé combinée dans chaque df
clust["_key"] = clust[cles].astype(str).agg("||".join, axis=1)
concord["_key"] = concord[cles].astype(str).agg("||".join, axis=1)

# Marquer s'ils existent dans df2
concord["trouve"] = concord["_key"].isin(clust["_key"])
clust["trouve"] = clust["_key"].isin(concord["_key"])

# Résultat final : seulement les individus de df1
df_result1 = clust.drop(columns="_key")
df_result2 = concord.drop(columns="_key")

In [60]:
df_result1

,cluster,age_num,sex,marital_status,city,milieu_resid,region_name,bancarise,trouve
0,17,29,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1,False
1,12,17,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,False
2,1,15,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,False
3,12,12,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,False
4,22,34,Féminin,Marié(e),ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,False
...,...,...,...,...,...,...,...,...,...
64469,89,11,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,False
64470,89,7,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,False
64471,89,10,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,False
64472,89,4,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,False
64473,85,36,Masculin,Marié(e),TIEMELEKRO,Rural,MORONOU,1,False

In [61]:
df_result2

,region_name,city,milieu_resid,sex,age_num,marital_status,bancarise,trouve
1,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,38,Célibataire,1,True
2,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,55,Célibataire,1,True
3,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,42,Célibataire,1,True
4,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,37,Célibataire,1,True
6,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Féminin,50,Union libre,1,True
...,...,...,...,...,...,...,...,...
24952,MORONOU,TIEMELEKRO,Rural,Masculin,0,Célibataire,0,True
24954,MORONOU,TIEMELEKRO,Rural,Masculin,26,Célibataire,0,True
24959,MORONOU,TIEMELEKRO,Rural,Masculin,65,Veuf(ve),1,True
24962,MORONOU,TIEMELEKRO,Rural,Féminin,33,Marié(e),0,True
24963,MORONOU,TIEMELEKRO,Rural,Féminin,37,Marié(e),0,True

In [62]:
DF_TRUE = df_result1[df_result1["trouve"]==True]
DF_TRUE

,cluster,age_num,sex,marital_status,city,milieu_resid,region_name,bancarise,trouve
10,94,38,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1,True
11,56,55,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1,True
17,94,42,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1,True
23,94,37,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1,True
38,22,50,Féminin,Union libre,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1,True
...,...,...,...,...,...,...,...,...,...
64443,89,0,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,True
64449,89,26,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,True
64456,13,65,Masculin,Veuf(ve),TIEMELEKRO,Rural,MORONOU,1,True
64466,6,33,Féminin,Marié(e),TIEMELEKRO,Rural,MORONOU,0,True
64468,24,37,Féminin,Marié(e),TIEMELEKRO,Rural,MORONOU,0,True

In [63]:
DF_TRUE["trouve"].unique()

array([ True])

In [64]:
df_result2[df_result2["trouve"]==True]

,region_name,city,milieu_resid,sex,age_num,marital_status,bancarise,trouve
1,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,38,Célibataire,1,True
2,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,55,Célibataire,1,True
3,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,42,Célibataire,1,True
4,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,37,Célibataire,1,True
6,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Féminin,50,Union libre,1,True
...,...,...,...,...,...,...,...,...
24952,MORONOU,TIEMELEKRO,Rural,Masculin,0,Célibataire,0,True
24954,MORONOU,TIEMELEKRO,Rural,Masculin,26,Célibataire,0,True
24959,MORONOU,TIEMELEKRO,Rural,Masculin,65,Veuf(ve),1,True
24962,MORONOU,TIEMELEKRO,Rural,Féminin,33,Marié(e),0,True
24963,MORONOU,TIEMELEKRO,Rural,Féminin,37,Marié(e),0,True

In [65]:
df_result2["trouve"].unique()

array([ True])

In [66]:
df_result1[df_result1["trouve"]==False]

,cluster,age_num,sex,marital_status,city,milieu_resid,region_name,bancarise,trouve
0,17,29,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1,False
1,12,17,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,False
2,1,15,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,False
3,12,12,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,False
4,22,34,Féminin,Marié(e),ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,False
...,...,...,...,...,...,...,...,...,...
64469,89,11,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,False
64470,89,7,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,False
64471,89,10,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,False
64472,89,4,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,False
64473,85,36,Masculin,Marié(e),TIEMELEKRO,Rural,MORONOU,1,False

In [67]:
print(DF_TRUE["cluster"].nunique())
DF_TRUE["cluster"].unique()

97

array([94, 56, 22,  1, 12, 17, 23, 11, 33, 34, 91,  3,  9, 60, 55, 92, 53,
       81,  8, 10, 71, 88,  7, 31, 13, 80, 77, 52, 21, 24, 85, 15,  2, 59,
       19, 25, 64, 14, 93, 68,  6, 76, 62, 50, 44, 72, 49, 90, 96, 83, 57,
       84, 36, 29, 38, 54, 78, 40, 61,  0, 45, 74,  4, 30, 79, 66, 48, 70,
       39, 95, 32, 28, 82, 27, 58, 35, 26, 47, 51, 16, 37, 65, 67,  5, 87,
       20, 46, 73, 86, 63, 42, 43, 18, 41, 69, 75, 89])

In [68]:
df_result1["cluster"].nunique()

97

In [69]:
clust_base = pd.read_csv("../DATAS/ANSTAT2021_clusters_PC.csv")
clust_base

,cluster,age_num,sex,marital_status,city,milieu_resid,region_name,bancarise
0,17,29,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1
1,12,17,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0
2,1,15,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0
3,12,12,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0
4,22,34,Féminin,Marié(e),ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0
...,...,...,...,...,...,...,...,...
64469,89,11,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0
64470,89,7,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0
64471,89,10,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0
64472,89,4,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0
64473,85,36,Masculin,Marié(e),TIEMELEKRO,Rural,MORONOU,1

In [70]:
clust_base_regle = pd.read_csv("./assigned_clusters_manual_rules.csv")
clust_base_regle

,cluster,age_num,sex,marital_status,city,milieu_resid,region_name,bancarise,age_group,predicted_cluster
0,17,29,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1,25-34,17
1,12,17,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,15-24,12
2,1,15,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,15-24,1
3,12,12,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,0-14,12
4,22,34,Féminin,Marié(e),ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,25-34,22
...,...,...,...,...,...,...,...,...,...,...
64469,89,11,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,0-14,89
64470,89,7,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,0-14,89
64471,89,10,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,0-14,89
64472,89,4,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,0-14,89
64473,85,36,Masculin,Marié(e),TIEMELEKRO,Rural,MORONOU,1,35-44,52

In [71]:
segm = pd.read_csv("./Rules Clusters/Segmentation_Results.csv")
segm

,cluster,age_num,sex,marital_status,city,milieu_resid,region_name,bancarise,agro_zone,department,...,fer,frigo,cuisin,ordin,decod,car,superf,volhor_manquant,salaire_mois_manquant,Stg_formel
0,17,29,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1,ABIDJAN,ABIDJAN,...,Non,Oui,Non,Non,Oui,Non,0.0,0,0,1
1,12,17,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,ABIDJAN,ABIDJAN,...,Non,Oui,Non,Non,Oui,Non,0.0,1,1,0
2,1,15,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,ABIDJAN,ABIDJAN,...,Non,Oui,Non,Non,Oui,Non,0.0,1,1,0
3,12,12,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,ABIDJAN,ABIDJAN,...,Non,Oui,Non,Non,Oui,Non,0.0,1,1,0
4,22,34,Féminin,Marié(e),ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,ABIDJAN,ABIDJAN,...,Non,Oui,Non,Non,Oui,Non,0.0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64469,89,11,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,CENTRE,M'BATTO,...,Non,Non,Non,Non,Oui,Non,8566398.0,1,1,0
64470,89,7,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,CENTRE,M'BATTO,...,Non,Non,Non,Non,Oui,Non,8566398.0,1,1,0
64471,89,10,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,CENTRE,M'BATTO,...,Non,Non,Non,Non,Oui,Non,8566398.0,1,1,0
64472,89,4,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,CENTRE,M'BATTO,...,Non,Non,Non,Non,Oui,Non,8566398.0,1,1,0
64473,52,36,Masculin,Marié(e),TIEMELEKRO,Rural,MORONOU,1,CENTRE,M'BATTO,...,Non,Non,Non,Non,Oui,Non,8566398.0,0,1,0

In [72]:
segm.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64474 entries, 0 to 64473
Data columns (total 71 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   cluster                64474 non-null  object
 1   age_num                64474 non-null  int64
 2   sex                    64474 non-null  object
 3   marital_status         64474 non-null  object
 4   city                   64474 non-null  object
 5   milieu_resid           64474 non-null  object
 6   region_name            64474 non-null  object
 7   bancarise              64474 non-null  int64
 8   agro_zone              64474 non-null  object
 9   department             64474 non-null  object
 10  hhweight               64474 non-null  float64
 11  resid                  64474 non-null  object
 12  lien                   64474 non-null  object
 13  religion               64474 non-null  object
 14  ethnie                 64474 non-null  object
 15  nation                 64474 non-null  object
 16  agemar                 64474 non-null  float64
 17  mal30j                 64474 non-null  object
 18  aff30j                 64474 non-null  object
 19  arrmal                 64474 non-null  object
 20  durarr                 64474 non-null  object
 21  con30j                 64474 non-null  object
 22  hos12m                 64474 non-null  object
 23  couvmal                64474 non-null  object
 24  handit                 64474 non-null  object
 25  handig                 64474 non-null  object
 26  alfa                   64474 non-null  object
 27  alfa2                  64474 non-null  object
 28  scol                   64474 non-null  object
 29  educ_scol              64474 non-null  object
 30  educ_hi                64474 non-null  object
 31  diplome                64474 non-null  object
 32  telpor                 64474 non-null  object
 33  internet               64474 non-null  object
 34  activ7j                64474 non-null  object
 35  activ12m               64474 non-null  object
 36  branch                 64474 non-null  object
 37  sectins                64474 non-null  object
 38  csp                    64474 non-null  object
 39  volhor                 64474 non-null  float64
 40  salaire                64474 non-null  float64
 41  emploi_sec             64474 non-null  object
 42  sectins_sec            64474 non-null  object
 43  csp_sec                64474 non-null  object
 44  volhor_sec             64474 non-null  float64
 45  salaire_sec            64474 non-null  int64
 46  serviceconsult         64474 non-null  object
 47  persconsult            64474 non-null  object
 48  salaire_mois           64474 non-null  float64
 49  salaire_sec_mois       64474 non-null  float64
 50  rev_total_mois         64474 non-null  float64
 51  log_revenu             64474 non-null  float64
 52  sans_revenu            64474 non-null  int64
 53  age_grp                64474 non-null  object
 54  a_assurance            64474 non-null  int64
 55  alphabete              64474 non-null  int64
 56  logem                  64474 non-null  object
 57  elec_ac                64474 non-null  object
 58  elec_ur                64474 non-null  object
 59  elec_ua                64474 non-null  object
 60  tv                     64474 non-null  object
 61  fer                    64474 non-null  object
 62  frigo                  64474 non-null  object
 63  cuisin                 64474 non-null  object
 64  ordin                  64474 non-null  object
 65  decod                  64474 non-null  object
 66  car                    64474 non-null  object
 67  superf                 64474 non-null  float64
 68  volhor_manquant        64474 non-null  int64
 69  salaire_mois_manquant  64474 non-null  int64
 70  Stg_formel             64474 non-null  int64
dtypes: float64(10), int64(9), object(52)
memory usage: 34.9+ MB

In [73]:
segm[segm["cluster"]!="Aucun"]

,cluster,age_num,sex,marital_status,city,milieu_resid,region_name,bancarise,agro_zone,department,...,fer,frigo,cuisin,ordin,decod,car,superf,volhor_manquant,salaire_mois_manquant,Stg_formel
0,17,29,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1,ABIDJAN,ABIDJAN,...,Non,Oui,Non,Non,Oui,Non,0.0,0,0,1
1,12,17,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,ABIDJAN,ABIDJAN,...,Non,Oui,Non,Non,Oui,Non,0.0,1,1,0
2,1,15,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,ABIDJAN,ABIDJAN,...,Non,Oui,Non,Non,Oui,Non,0.0,1,1,0
3,12,12,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,ABIDJAN,ABIDJAN,...,Non,Oui,Non,Non,Oui,Non,0.0,1,1,0
4,22,34,Féminin,Marié(e),ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,ABIDJAN,ABIDJAN,...,Non,Oui,Non,Non,Oui,Non,0.0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64469,89,11,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,CENTRE,M'BATTO,...,Non,Non,Non,Non,Oui,Non,8566398.0,1,1,0
64470,89,7,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,CENTRE,M'BATTO,...,Non,Non,Non,Non,Oui,Non,8566398.0,1,1,0
64471,89,10,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,CENTRE,M'BATTO,...,Non,Non,Non,Non,Oui,Non,8566398.0,1,1,0
64472,89,4,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,CENTRE,M'BATTO,...,Non,Non,Non,Non,Oui,Non,8566398.0,1,1,0
64473,52,36,Masculin,Marié(e),TIEMELEKRO,Rural,MORONOU,1,CENTRE,M'BATTO,...,Non,Non,Non,Non,Oui,Non,8566398.0,0,1,0

In [74]:
segm.columns

Index(['cluster', 'age_num', 'sex', 'marital_status', 'city', 'milieu_resid',
       'region_name', 'bancarise', 'agro_zone', 'department', 'hhweight',
       'resid', 'lien', 'religion', 'ethnie', 'nation', 'agemar', 'mal30j',
       'aff30j', 'arrmal', 'durarr', 'con30j', 'hos12m', 'couvmal', 'handit',
       'handig', 'alfa', 'alfa2', 'scol', 'educ_scol', 'educ_hi', 'diplome',
       'telpor', 'internet', 'activ7j', 'activ12m', 'branch', 'sectins', 'csp',
       'volhor', 'salaire', 'emploi_sec', 'sectins_sec', 'csp_sec',
       'volhor_sec', 'salaire_sec', 'serviceconsult', 'persconsult',
       'salaire_mois', 'salaire_sec_mois', 'rev_total_mois', 'log_revenu',
       'sans_revenu', 'age_grp', 'a_assurance', 'alphabete', 'logem',
       'elec_ac', 'elec_ur', 'elec_ua', 'tv', 'fer', 'frigo', 'cuisin',
       'ordin', 'decod', 'car', 'superf', 'volhor_manquant',
       'salaire_mois_manquant', 'Stg_formel'],
      dtype='object')

In [75]:
keys = ["marital_status", "bancarise", "city", "milieu_resid", "age_num", "sex", "region_name"]

# s'assurer que les colonnes existent et sont comparables (str)
for c in keys:
    segm[c] = segm[c].astype(str)
    concordant[c] = concordant[c].astype(str)

# merge avec indicateur puis garder les "left_only" (présents dans segm mais pas dans concordant)
segm_not_in_concordant = segm.merge(
    concordant[keys].drop_duplicates(),
    on=keys,
    how="left",
    indicator=True
)
segm_not_in_concordant = segm_not_in_concordant[segm_not_in_concordant["_merge"] == "left_only"].drop(columns=["_merge"])
segm_not_in_concordant

,cluster,age_num,sex,marital_status,city,milieu_resid,region_name,bancarise,agro_zone,department,...,fer,frigo,cuisin,ordin,decod,car,superf,volhor_manquant,salaire_mois_manquant,Stg_formel
0,17,29,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1,ABIDJAN,ABIDJAN,...,Non,Oui,Non,Non,Oui,Non,0.000000e+00,0,0,1
1,12,17,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,ABIDJAN,ABIDJAN,...,Non,Oui,Non,Non,Oui,Non,0.000000e+00,1,1,0
2,1,15,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,ABIDJAN,ABIDJAN,...,Non,Oui,Non,Non,Oui,Non,0.000000e+00,1,1,0
3,12,12,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,ABIDJAN,ABIDJAN,...,Non,Oui,Non,Non,Oui,Non,0.000000e+00,1,1,0
4,22,34,Féminin,Marié(e),ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0,ABIDJAN,ABIDJAN,...,Non,Oui,Non,Non,Oui,Non,0.000000e+00,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64467,75,12,Féminin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,CENTRE,M'BATTO,...,Non,Non,Non,Non,Non,Non,3.217664e+07,1,1,0
64469,89,11,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,CENTRE,M'BATTO,...,Non,Non,Non,Non,Oui,Non,8.566398e+06,1,1,0
64470,89,7,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,CENTRE,M'BATTO,...,Non,Non,Non,Non,Oui,Non,8.566398e+06,1,1,0
64471,89,10,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,CENTRE,M'BATTO,...,Non,Non,Non,Non,Oui,Non,8.566398e+06,1,1,0
64472,89,4,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0,CENTRE,M'BATTO,...,Non,Non,Non,Non,Oui,Non,8.566398e+06,1,1,0

In [79]:
segm_not_in_concordant.columns

Index(['cluster', 'age_num', 'sex', 'marital_status', 'city', 'milieu_resid',
       'region_name', 'bancarise', 'agro_zone', 'department', 'hhweight',
       'resid', 'lien', 'religion', 'ethnie', 'nation', 'agemar', 'mal30j',
       'aff30j', 'arrmal', 'durarr', 'con30j', 'hos12m', 'couvmal', 'handit',
       'handig', 'alfa', 'alfa2', 'scol', 'educ_scol', 'educ_hi', 'diplome',
       'telpor', 'internet', 'activ7j', 'activ12m', 'branch', 'sectins', 'csp',
       'volhor', 'salaire', 'emploi_sec', 'sectins_sec', 'csp_sec',
       'volhor_sec', 'salaire_sec', 'serviceconsult', 'persconsult',
       'salaire_mois', 'salaire_sec_mois', 'rev_total_mois', 'log_revenu',
       'sans_revenu', 'age_grp', 'a_assurance', 'alphabete', 'logem',
       'elec_ac', 'elec_ur', 'elec_ua', 'tv', 'fer', 'frigo', 'cuisin',
       'ordin', 'decod', 'car', 'superf', 'volhor_manquant',
       'salaire_mois_manquant', 'Stg_formel'],
      dtype='object')

In [80]:
segm_not_in_concordant = segm_not_in_concordant.drop(['agro_zone', 'department', 'hhweight',
       'resid', 'lien', 'religion', 'ethnie', 'nation', 'agemar', 'mal30j',
       'aff30j', 'arrmal', 'durarr', 'con30j', 'hos12m', 'couvmal', 'handit',
       'handig', 'alfa', 'alfa2', 'scol', 'educ_scol', 'educ_hi', 'diplome',
       'telpor', 'internet', 'activ7j', 'activ12m', 'branch', 'sectins', 'csp',
       'volhor', 'salaire', 'emploi_sec', 'sectins_sec', 'csp_sec',
       'volhor_sec', 'salaire_sec', 'serviceconsult', 'persconsult',
       'salaire_mois', 'salaire_sec_mois', 'rev_total_mois', 'log_revenu',
       'sans_revenu', 'age_grp', 'a_assurance', 'alphabete', 'logem',
       'elec_ac', 'elec_ur', 'elec_ua', 'tv', 'fer', 'frigo', 'cuisin',
       'ordin', 'decod', 'car', 'superf', 'volhor_manquant',
       'salaire_mois_manquant', 'Stg_formel'], axis=1)
segm_not_in_concordant

,cluster,age_num,sex,marital_status,city,milieu_resid,region_name,bancarise
0,17,29,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,1
1,12,17,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0
2,1,15,Masculin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0
3,12,12,Féminin,Célibataire,ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0
4,22,34,Féminin,Marié(e),ABIDJAN,Urbain,AUTONOME D'ABIDJAN,0
...,...,...,...,...,...,...,...,...
64467,75,12,Féminin,Célibataire,TIEMELEKRO,Rural,MORONOU,0
64469,89,11,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0
64470,89,7,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0
64471,89,10,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0
64472,89,4,Masculin,Célibataire,TIEMELEKRO,Rural,MORONOU,0

In [81]:
# Grouper et compter les individus par cluster dans segm_not_in_concordant
cluster_counts = (
    segm_not_in_concordant['cluster']
    .value_counts(dropna=False)
    .rename_axis('cluster')
    .reset_index(name='count')
    .sort_values('count', ascending=False)
)

# ajouter pourcentage
cluster_counts['pct'] = (cluster_counts['count'] / cluster_counts['count'].sum()).round(4)

# afficher
cluster_counts

   cluster  count     pct
0       55   1544  0.0391
1        6   1266  0.0320
2       24   1235  0.0313
3       77   1199  0.0303
4       71   1156  0.0293
..     ...    ...     ...
92      30    152  0.0038
93       5    144  0.0036
94       2    136  0.0034
95      75    121  0.0031
96      42     72  0.0018

[97 rows x 3 columns]

In [83]:
cluster_counts['cluster'].unique()

array(['55', '6', '24', '77', '71', '15', '12', '14', '52', '3', '1',
       '81', '53', '84', '85', '60', '21', '61', '31', '64', '92', '9',
       '10', '8', '36', '19', '22', '18', '95', '43', '7', '94', '25',
       '69', '76', '88', '79', '13', '17', '20', '32', '16', '50', '59',
       '41', '34', '35', '45', '37', '80', '78', '83', '51', '49', '72',
       '73', '23', '87', '74', '56', '11', '26', '68', '70', '65', '82',
       '57', '48', '38', '28', '0', '62', '40', '47', '66', '39', '86',
       '67', '58', '4', '90', '33', '89', '96', '27', '93', '54', '91',
       '63', '46', '44', '29', '30', '5', '2', '75', '42'], dtype=object)

In [ ]:
segm_not_in_concordant["cluster"].value_counts()

cluster
55    1544
6     1266
24    1235
77    1199
71    1156
      ...
30     152
5      144
2      136
75     121
42      72
Name: count, Length: 97, dtype: int64

In [46]:
concord1 = concord.drop(['_key'], axis=1)
concord1

,region_name,city,milieu_resid,sex,age_num,marital_status,bancarise,trouve
1,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,38,Célibataire,1,True
2,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,55,Célibataire,1,True
3,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,42,Célibataire,1,True
4,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Masculin,37,Célibataire,1,True
6,AUTONOME D'ABIDJAN,ABIDJAN,Urbain,Féminin,50,Union libre,1,True
...,...,...,...,...,...,...,...,...
24952,MORONOU,TIEMELEKRO,Rural,Masculin,0,Célibataire,0,True
24954,MORONOU,TIEMELEKRO,Rural,Masculin,26,Célibataire,0,True
24959,MORONOU,TIEMELEKRO,Rural,Masculin,65,Veuf(ve),1,True
24962,MORONOU,TIEMELEKRO,Rural,Féminin,33,Marié(e),0,True
24963,MORONOU,TIEMELEKRO,Rural,Féminin,37,Marié(e),0,True